### PR TITLE
DTSPO-5822 - ZRS Migration

### PR DESCRIPTION
**Pull request by endakelly**
Migration of storage accounts from LRS to ZRS

### CODE REVIEW

**Comment by endakelly** [comment]
> @endakelly presumably this change won't dump the existing blob storage contents and re-create it. It will just migrate the existing one?

Yes. Microsoft have migrated the fact storage accounts to ZRS in the background and the terraform plan shows no changes to the infrastructure. If the master branch was to be run now without this change, it would delete the ZRS account and recreate it as LRS.

**Comment by linusnorton** [comment]
I don't think it was set up in any other environments but I can't remember

**Review by linusnorton — APPROVED** [review]

**Comment by endakelly** [comment]
> I don't think it was set up in any other environments but I can't remember

Well there are demo, ithc and perftest branches and storage accounts

**Comment by endakelly** [comment]
> > I don't think it was set up in any other environments but I can't remember
> 
> Well there are demo, ithc and perftest branches and storage accounts

I remember the deal with these now actually. The other branches were to stay on LRS and we didn't ask Microsoft to migrate them so no further changes needed to other branches.

**Pull request merged**
